// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkyRoute.Infrastructure.Persistence;

#nullable disable

namespace SkyRoute.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SkyRouteDbContext))]
    [Migration("20260504213649_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("SkyRoute.Domain.Entities.Booking", b =>
                {
                    b.Property<string>("Reference")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Reference");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("SkyRoute.Domain.Entities.Booking", b =>
                {
                    b.OwnsOne("SkyRoute.Domain.ValueObjects.Money", "PricePerPassenger", b1 =>
                        {
                            b1.Property<string>("BookingReference")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("PricePerPassenger_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("PricePerPassenger_Currency");

                            b1.HasKey("BookingReference");

                            b1.ToTable("Bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingReference");
                        });

                    b.OwnsOne("SkyRoute.Domain.ValueObjects.Money", "TotalPrice", b1 =>
                        {
                            b1.Property<string>("BookingReference")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("TotalPrice_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("TotalPrice_Currency");

                            b1.HasKey("BookingReference");

                            b1.ToTable("Bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingReference");
                        });

                    b.OwnsOne("SkyRoute.Domain.Entities.Flight", "Flight", b1 =>
                        {
                            b1.Property<string>("BookingReference")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("ArrivalTime")
                                .HasColumnType("TEXT")
                                .HasColumnName("Flight_ArrivalTime");

                            b1.Property<string>("CabinClass")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("Flight_CabinClass");

                            b1.Property<DateTime>("DepartureTime")
                                .HasColumnType("TEXT")
                                .HasColumnName("Flight_DepartureTime");

                            b1.Property<string>("FlightId")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("Flight_FlightId");

                            b1.Property<string>("FlightNumber")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("Flight_FlightNumber");

                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("Flight_Provider");

                            b1.HasKey("BookingReference");

                            b1.ToTable("Bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingReference");

                            b1.OwnsOne("SkyRoute.Domain.ValueObjects.Money", "BaseFare", b2 =>
                                {
                                    b2.Property<string>("FlightBookingReference")
                                        .HasColumnType("TEXT");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("Flight_BaseFare_Amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("Flight_BaseFare_Currency");

                                    b2.HasKey("FlightBookingReference");

                                    b2.ToTable("Bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("FlightBookingReference");
                                });

                            b1.OwnsOne("SkyRoute.Domain.Entities.Airport", "Destination", b2 =>
                                {
                                    b2.Property<string>("FlightBookingReference")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("Flight_Destination_City");

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("Flight_Destination_Code");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasMaxLength(2)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("Flight_Destination_Country");

                                    b2.Property<string>("CountryName")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("Flight_Destination_CountryName");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("Flight_Destination_Name");

                                    b2.HasKey("FlightBookingReference");

                                    b2.ToTable("Bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("FlightBookingReference");
                                });

                            b1.OwnsOne("SkyRoute.Domain.Entities.Airport", "Origin", b2 =>
                                {
                                    b2.Property<string>("FlightBookingReference")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("Flight_Origin_City");

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("Flight_Origin_Code");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasMaxLength(2)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("Flight_Origin_Country");

                                    b2.Property<string>("CountryName")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("Flight_Origin_CountryName");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("Flight_Origin_Name");

                                    b2.HasKey("FlightBookingReference");

                                    b2.ToTable("Bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("FlightBookingReference");
                                });

                            b1.Navigation("BaseFare")
                                .IsRequired();

                            b1.Navigation("Destination")
                                .IsRequired();

                            b1.Navigation("Origin")
                                .IsRequired();
                        });

                    b.OwnsMany("SkyRoute.Domain.Entities.Passenger", "Passengers", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("BookingReference")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("DocumentNumber")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("BookingReference");

                            b1.ToTable("BookingPassengers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BookingReference");
                        });

                    b.Navigation("Flight")
                        .IsRequired();

                    b.Navigation("Passengers");

                    b.Navigation("PricePerPassenger")
                        .IsRequired();

                    b.Navigation("TotalPrice")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
